#!/usr/bin/env bash
# Script transfer files to server remotely

if [[ ! $4 ]]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
    scp -o StrinctHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
if

