#!/usr/bin/env bash
# Script install nginx server and configure it to return
# Hello World! when there is a GET request to root

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod 777 -R /var/www/html
echo "Hello World!" > /var/www/html/index.html
service nginx start

