#!/usr/bin/env bash
# Script configures ubuntu machine for url redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.browniwils.tech permnant;"

sudo service nginx restart

