#!/usr/bin/env bash
# Script install and configure nginx server for redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
redirect="\\\trewrite ^/redirect_me https:\/\/www.browniwils.tech permnant;

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
line="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /user/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $line" /etc/nginx/sites-available/default
if [[ $(pgrep nginx) ]]; then
	sudo nginx -s reload
else
	sduo service nginx start
fi

