#!/usr/bin/env bash
# This program kills program running program pid 
# of file "./4-to_infinity_and_beyond" and kills it

id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

if [ -n "$id" ]
then
	kill -15 "$id"
fi
