#!/usr/bin/env bash
# This program when run creates a file named holbertonscript.pid
# at directory /var/run containing it's PID
# where it shows "To infinity and beyond" in a continous loop
# shows "Y U no love me?! when SIGINT signal is received

function love() {
	rm /var/run/holbertonscript.pid
	exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while [ true ];
do
	echo "To infinity and beyond";
done
