#!/usr/bin/env bash
# Program displays numbers from 1 - 100
# and at where number is multiple of 3 and 5 FizzBuzz is displayed
# and at where number is multiple of 3 Fizz is displayed and
# at where number is multiples of 5 Buzz is displayed instead of their 
# respective numbers

for n in {1..100}
do
	if (( n % 3 == 0 && n % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( n % 3 == 0 ))
	then
		echo "Fizz"
	elif (( n % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$n"
	fi
done
