#!/usr/bin/env bash
# This program displays "Best School" 10 times
# but on the 9th turn, it displays "Hi" before "Best School"

c=0

while [ $c -lt 10 ]
do
	if [ $c -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( c++ ))
done
