#!/usr/bin/env bash
# Program loops 10 times and displays
# "bad luck" for the 4th run, "good luck"
# for the 8th run, then "Best School"
# for all other run

c=0

while [ $c -lt 10 ]
do
	if [ $c -eq 3 ]
	then
		echo "bad luck"
	elif [ $c -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( c++ ))
done
