#!/usr/bin/env bash
# Program displays 1 - 20 number with
# other inscriptions

c=1

while [ $c -le 20 ]
do
	echo "$c"
	case $c in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( c++ ))
done
