#!/usr/bin/env bash
# This program when run shows active internet protocol
# version 4 IPv4 on the machine currently runing this program

ifconfig | grep -Po 'inet addr:\K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
